services:
  web:
    build:
    image: php:8.1-apache
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    networks:
      - default
  db:
    image: mysql:latest
    container_name: web-mysql
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_DATABASE: exampledb
    ports:
      - "3306:3306"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - default
